create table products (
    id bigint primary key generated by default as identity,
    name text not null,
    price int not null,
    inserted_at timestamp(0) not null default (now() at time zone 'UTC'),
    updated_at timestamp(0) not null default (now() at time zone 'UTC'),
    check (price >= 0)
);
